### ISSUE TITLE
quarantine enforcement

### ISSUE THREAD

**Issue by andreiyurkevich** [enigmampc/SafeTrace#10]
If the quarantine is mandated by law enforcement agencies then some features of location tracking can be used. 
- Law enforcement agency is notified when a quarantined person leaves his/her location. 
- Quarantined person is requested to take a geo-located selfie 

More details are here
https://www.businessinsider.com/poland-app-coronavirus-patients-mandaotory-selfie-2020-3

**Comment by ainsleys** [comment]
A few issues with using contact-tracing for this type of monitoring:
- we aren't yet ingesting live data (that would probably require a mobile app front-end)
- this definitely wouldn't be privacy-preserving, is there any reason LEO to use a privacy-preserving system rather than a standard GPS tracker w/ notis if they have that mandate?

**Comment by ainsleys** [comment]
Closing this because there's no next steps at this time, feel free to reopen if you feel differently @andreiyurkevich
